apiVersion: v1
kind: Service
metadata:
  name: ql-file-net
  namespace: quantumleap
spec:
  type: ClusterIP
  selector:
    app: ql-file-net
    release: "1.0.0"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ql-file-net
  namespace: quantumleap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ql-file-net
      release: "1.0.0"
  template:
    metadata:
      labels:
        app: ql-file-net
        release: "1.0.0"
    spec:
      containers:
        - name: ql-file-net
          image: 'ql:file-net-1.0.0'
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: config